name: 'ops_dbt'
version: '1.0.0'
config-version: 2

profile: 'ops_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ops_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
