version: 2

sources:
  - name: sample
    database: sample_db
    schema: sample_schema
    tables:
      - name: ORDERS
      - name: CUSTOMER
      - name: ORDERS_SIMULATED
      - name: RAW_ORDERS
